const mongoose = require('mongoose');
const { Device, Supplier, DeviceType, Location } = require('../models/models');

mongoose.connect('mongodb://127.0.0.1:27017/CSVC', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
});

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'Connection error:'));
db.once('open', async () => {
  try {
    // Example data
    const suppliers = await Supplier.find();
    const deviceTypes = await DeviceType.find();
    const locations = await Location.find();

    const devicesData = [
      {
        serialNumber: 'MC00001',
        name: 'Máy chiếu',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '2000000',
        purchaseDate: new Date('2022-01-15'),
        warrantyExpiry: new Date('2025-01-15'),
        createDate: new Date(),
        depreciationRate: 15,
      },
      {
        serialNumber: 'MC00002',
        name: 'Máy chiếu',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'notUsed',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '2000',
        purchaseDate: new Date('2023-03-22'),
        warrantyExpiry: new Date('2026-03-22'),
        createDate: new Date(),
        depreciationRate: 15,
      },
      {
        serialNumber: 'MC00003',
        name: 'Máy chiếu',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '1500',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MH00001',
        name: 'Màn hình',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '5000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MH00002',
        name: 'Màn hình',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '5000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MA00001',
        name: 'Máy ảnh',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '3000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MA00002',
        name: 'Máy ảnh',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '3000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MA00003',
        name: 'Máy ảnh',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '3000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MA00004',
        name: 'Máy ảnh',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '3000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MT00001',
        name: 'Máy tính',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MT00002',
        name: 'Máy tính',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MT00003',
        name: 'Máy tính',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MT00004',
        name: 'Máy tính',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MT00005',
        name: 'Máy tính',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MT00006',
        name: 'Máy tính',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MT00007',
        name: 'Máy tính',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'MT00008',
        name: 'Máy tính',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'DT00001',
        name: 'Điện thoại',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '10000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'DT00002',
        name: 'Điện thoại',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '10000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'DT00003',
        name: 'Điện thoại',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '10000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'PLC00001',
        name: 'Mô hình thí nghiệm PLC',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '100000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'PLC00002',
        name: 'Mô hình thí nghiệm PLC',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '10000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'FMS00001',
        name: 'Hệ thống sản xuất linh hoạt',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'FMS00002',
        name: 'Hệ thống sản xuất linh hoạt',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '14000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'KIT00001',
        name: 'Bộ công cụ thí nghiệm giáo dục công nghiệp 4.0',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '99000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      {
        serialNumber: 'KIT00002',
        name: 'Bộ công cụ thí nghiệm giáo dục công nghiệp 4.0',
        deviceType: deviceTypes[0]._id,
        status: 'Active',
        initStatus: 'used',
        location: locations[0]._id,
        supplier: suppliers[0]._id,
        description: '',
        price: '99000000',
        purchaseDate: new Date('2021-08-30'),
        warrantyExpiry: new Date('2024-08-30'),
        createDate: new Date(),
        depreciationRate: 12,
      },
      
    ];

    // Insert the devices
    await Device.insertMany(devicesData);

    console.log('Devices data inserted successfully!');
    mongoose.disconnect();
  } catch (err) {
    console.error('Error inserting device data:', err);
    mongoose.disconnect();
  }
});